spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
          - Path=/auth/**

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
