spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/foodles
      database: foodles
      username: admin
      password: ak12345
  jpa:
    hibernate:
      ddl-auto: true
    show-sql: true


server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret-key: 23c24bfd4f0c98f4da9a34beae732f13d4c79cc3d2529d445d43071ad8c764bb
    expiration-time: 300000
  refresh-token:
    expiration-time: 600000

springdoc:
  api-docs:
    path: /api-docs

